CREATE TABLE [dbo].[BodyParts](
	[BodyPartId] [varchar](5) NOT NULL,
	[BodyPartName] [varchar](100) NOT NULL,
 CONSTRAINT [PK_BodyParts] PRIMARY KEY CLUSTERED 
(
	[BodyPartId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO